package ru.harionovsky.bunstore.models;
// Generated 24.10.2017 16:31:27 by Hibernate Tools 4.3.1



/**
 * Orders generated by hbm2java
 */
public class Orders  implements java.io.Serializable {


     private int id;
     private String fio;
     private String fhone;
     private String address;
     private Boolean isdone;

    public Orders() {
    }

	
    public Orders(int id, String fio, String fhone, String address) {
        this.id = id;
        this.fio = fio;
        this.fhone = fhone;
        this.address = address;
    }
    public Orders(int id, String fio, String fhone, String address, Boolean isdone) {
       this.id = id;
       this.fio = fio;
       this.fhone = fhone;
       this.address = address;
       this.isdone = isdone;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getFio() {
        return this.fio;
    }
    
    public void setFio(String fio) {
        this.fio = fio;
    }
    public String getFhone() {
        return this.fhone;
    }
    
    public void setFhone(String fhone) {
        this.fhone = fhone;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Boolean getIsdone() {
        return this.isdone;
    }
    
    public void setIsdone(Boolean isdone) {
        this.isdone = isdone;
    }




}


