package ru.harionovsky.bunstore.models;
// Generated 24.10.2017 16:31:27 by Hibernate Tools 4.3.1



/**
 * Reserve generated by hbm2java
 */
public class Reserve  implements java.io.Serializable {


     private int id;
     private int wareid;
     private int orderid;
     private int quantity;

    public Reserve() {
    }

    public Reserve(int id, int wareid, int orderid, int quantity) {
       this.id = id;
       this.wareid = wareid;
       this.orderid = orderid;
       this.quantity = quantity;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getWareid() {
        return this.wareid;
    }
    
    public void setWareid(int wareid) {
        this.wareid = wareid;
    }
    public int getOrderid() {
        return this.orderid;
    }
    
    public void setOrderid(int orderid) {
        this.orderid = orderid;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }




}


