package ru.harionovsky.bunstore.models;
// Generated 24.10.2017 16:31:27 by Hibernate Tools 4.3.1



/**
 * Warehouse generated by hbm2java
 */
public class Warehouse  implements java.io.Serializable {


     private int id;
     private int wareid;
     private int quantity;

    public Warehouse() {
    }

    public Warehouse(int id, int wareid, int quantity) {
       this.id = id;
       this.wareid = wareid;
       this.quantity = quantity;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getWareid() {
        return this.wareid;
    }
    
    public void setWareid(int wareid) {
        this.wareid = wareid;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }




}


